name: ArchLinux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [g++-10, clang++-10]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt update ; sudo apt upgrade
          sudo apt install g++-10 clang lld llvm googletest

      - name: Configure
        run: cmake -S . -B build
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config Release -j$(nproc)

      - name: Test
        run: cd build ; ctest -C Release -j$(nproc) --output-on-failure
