name: Benchmark

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt update
          sudo apt install gcc-10 g++-10
          wget -q https://github.com/google/benchmark/archive/v1.5.2.zip
          unzip -q v1.5.2.zip
          cd benchmark-1.5.2
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_TESTING=OFF \
          -DBENCHMARK_ENABLE_LTO=ON -DBENCHMARK_ENABLE_GTEST_TESTS=OFF \
          -DBUILD_SHARED_LIBS=ON
          cmake --build build --config Release -j$(nproc)
          sudo cmake --build build --config Release --target install
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Configure
        run: cmake -S . -B build -DBENCHMARK=ON
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Build
        run: cmake --build build --config Release -j$(nproc)

      - name: Run
        run: cd build ; ./test-program-benchmark --benchmark_format=json | tee benchmark-result.json

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: C++ Benchmark Linux
          tool: "googlecpp"
          output-file-path: build/benchmark-result.json
          fail-on-alert: true
          alert-threshold: "120%"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          alert-comment-cc-users: "@KaiserLancelot"
          auto-push: true

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          ln -s "$(brew --prefix llvm)/bin/llvm-ar" "/usr/local/bin/llvm-ar"
          ln -s "$(brew --prefix llvm)/bin/llvm-nm" "/usr/local/bin/llvm-nm"
          wget -q https://github.com/google/benchmark/archive/v1.5.2.zip
          unzip -q v1.5.2.zip
          cd benchmark-1.5.2
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_TESTING=OFF \
          -DBENCHMARK_ENABLE_LTO=ON -DBENCHMARK_ENABLE_GTEST_TESTS=OFF \
          -DBUILD_SHARED_LIBS=ON
          cmake --build build --config Release -j`sysctl -n hw.ncpu`
          sudo cmake --build build --config Release --target install

      - name: Configure
        run: cmake -S . -B build -DBENCHMARK=ON

      - name: Build
        run: cmake --build build --config Release -j`sysctl -n hw.ncpu`
        env:
          C_INCLUDE_PATH: /usr/local/include
          CPLUS_INCLUDE_PATH: /usr/local/include

      - name: Run
        run: cd build ; ./test-program-benchmark --benchmark_format=json | tee benchmark-result.json

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: C++ Benchmark macOS
          tool: "googlecpp"
          output-file-path: build/benchmark-result.json
          fail-on-alert: true
          alert-threshold: "120%"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          alert-comment-cc-users: "@KaiserLancelot"
          auto-push: true
