name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - uses: actions/checkout@v1

    - name: install gtest
      run: pacman -Syu --noconfirm && pacman -S --noconfirm gcc make cmake intel-tbb boost fmt nlohmann-json gtest

    - name: configure
      run: mkdir build && cd build && cmake ..

    - name: build
      run: cmake --build build

    - name: test
      run: cd build && ctest
