name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install gtest
      run: sudo apt install unzip wget && \
      wget https://github.com/google/googletest/archive/release-1.10.0.zip && \
      unzip release-1.10.0.zip

    - name: configure
      run: mkdir build && cd build && cmake ..

    - name: build
      run: make -j8

    - name: test
      run: make test
