name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - uses: actions/checkout@v1

    - name: install gtest
      run: pacman -Syu && \
      pacman -S \
      gcc \
      make \
      cmake \
      intel-tbb \
      boost \
      fmt \
      nlohmann-json \
      gtest

    - name: configure
      run: mkdir build && cd build && cmake ..

    - name: build
      run: make -j8

    - name: test
      run: make test
