name: Clang-Tidy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt install g++10 llvm-toolchain-10 googletest

      - name: Configure
        env:
          CXX: g++10
        run: cmake -S . -B build -DCLANG_TIDY=ON

      - name: Build
        run: cmake --build build -j$(nproc)
