name: Clang-Tidy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang cmake gtest

      - name: Configure
        run: cmake -S . -B build -DCLANG_TIDY=ON

      - name: Build
        run: cmake --build build -j$(nproc)
