name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang lld llvm cmake gtest

      - name: Configure
        run: cmake -S . -B build -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
        env:
          CXX: clang++

      - name: Build
        run: cmake --build build -j$(nproc) --target coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/lcov.info
