name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt install g++10 googletest lcov

      - name: Configure
        env:
          CXX: ${{ g++-10 }}
        run: cmake -S . -B build -DCOVERAGE=ON

      - name: Build
        run: cmake --build build -j$(nproc) --target covergae

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/lcov.info
