name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang lld llvm cmake gtest wget
          wget https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz
          tar -xzvf lcov-1.15.tar.gz
          cd lcov-1.15
          make install

      - name: Configure
        run: cmake -S . -B build -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config Debug -j$(nproc) --target coverage

      - name: Coveralls
        if: ${{ matrix.compiler == 'clang++' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/lcov.info
