name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries and tools
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang lld llvm cmake wget gtest
          wget https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz
          tar -xzvf lcov-1.15.tar.gz
          cd lcov-1.15
          make install

      - name: CMake
        env:
          CXX: ${{ matrix.compiler }}
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=TRUE ..

      - name: Gather coverage data
        run: cmake --build build -j$(nproc) --target coverage

      - name: Codecov upload
        if: ${{ matrix.compiler == 'clang++' }}
        uses: codecov/codecov-action@v1
        with:
          file: build/coverage.info
          fail_ci_if_error: true
