name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          brew install unzip
          wget https://github.com/google/googletest/archive/release-1.10.0.zip
          unzip release-1.10.0.zip
          cd googletest-release-1.10.0
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j`sysctl -n hw.ncpu`
          sudo cmake --build build --target install
          echo "export CPLUS_INCLUDE_PATH=/usr/local/include" >> ~/.bash_profile
          echo "export LIBRARY_PATH=/usr/local/lib" >> ~/.bash_profile
          source ~/.bash_profile

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -j`sysctl -n hw.ncpu`

      - name: Test
        run: cd build ; ctest -j`sysctl -n hw.ncpu` --output-on-failure
