name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          brew install unzip
          wget https://github.com/google/googletest/archive/release-1.10.0.zip
          unzip release-1.10.0.zip
          cd googletest-release-1.10.0
          cmake -S . -B build
          cmake --build build -j`sysctl -n hw.ncpu`
          cmake --build build --target install

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -j`sysctl -n hw.ncpu`

      - name: Test
        run: cd build ; ctest -j`sysctl -n hw.ncpu` --output-on-failure
