name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm gcc make cmake \
        intel-tbb boost fmt nlohmann-json gtest wget unzip git
        wget https://github.com/Neargye/magic_enum/archive/v0.6.5.zip
        unzip v0.6.5.zip
        cd magic_enum-0.6.5
        mkdir build && cd build && cmake ..
        make -j4
        make install
        git clone https://github.com/linux-test-project/lcov
        cd lcov
        make install

    - name: configure
      run: mkdir build && cd build && cmake ..

    - name: build
      run: cd build && make -j4

    - name: test
      run: cd build && ctest

    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.info
