name: Release

on:
  release:
    types: published

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${TAG_NAME:1}
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Configure
        run: cmake -S . -B build
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Build
        run: cmake --build build --config Release -j$(nproc)

      - name: CPack
        run: cd build ; cpack

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/cpp-template-${{ env.RELEASE_VERSION }}-Linux.deb
          asset_name: cpp-template-${{ env.RELEASE_VERSION }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

  # TODO check
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${TAG_NAME:1}
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release -j`sysctl -n hw.ncpu`
        env:
          C_INCLUDE_PATH: /usr/local/include
          CPLUS_INCLUDE_PATH: /usr/local/include

      - name: CPack
        run: cd build ; cpack

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/cpp-template-${{ env.RELEASE_VERSION }}-Darwin.dmg
          asset_name: cpp-template-${{ env.RELEASE_VERSION }}-Darwin.dmg
          asset_content_type: application/x-apple-diskimage
