name: Sanitizer

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [g++-10, clang++-10]
        sanitizer: [Address, Thread, Undefined]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt update
          sudo apt install g++-10 clang
          wget https://github.com/google/googletest/archive/release-1.10.0.zip
          unzip release-1.10.0.zip
          cd googletest-release-1.10.0
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_GMOCK=OFF \
          -DBUILD_SHARED_LIBS=ON -Dgtest_build_tests=OFF
          cmake --build build --config Release -j$(nproc)
          sudo cmake --build build --config Release --target install
        env:
          CC: /usr/bin/gcc-10
          CXX: /usr/bin/g++-10

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSANITIZER=${{ matrix.sanitizer }}
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config RelWithDebInfo -j$(nproc)

      - name: Test
        run: cd build ; ctest -C RelWithDebInfo -j$(nproc) --output-on-failure

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        sanitizer: [Address, Thread, Undefined]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          brew update
          wget https://github.com/google/googletest/archive/release-1.10.0.zip
          unzip release-1.10.0.zip
          cd googletest-release-1.10.0
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_GMOCK=OFF \
          -DBUILD_SHARED_LIBS=ON -Dgtest_build_tests=OFF
          cmake --build build --config Release -j`sysctl -n hw.ncpu`
          sudo cmake --build build --config Release --target install

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSANITIZER=${{ matrix.sanitizer }}

      - name: Build
        run: cmake --build build --config RelWithDebInfo -j`sysctl -n hw.ncpu`
        env:
          C_INCLUDE_PATH: /usr/local/include
          CPLUS_INCLUDE_PATH: /usr/local/include

      - name: Test
        run: cd build ; ctest -C RelWithDebInfo -j`sysctl -n hw.ncpu` --output-on-failure
        # FIXME
        # env:
          # ASAN_OPTIONS: detect_leaks=1
