name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    # TODO use ubuntu-latest
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [g++-10, clang++-10]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: sudo apt install g++10 llvm-toolchain-10 googletest

      - name: Configure
        env:
          CXX: ${{ matrix.compiler }}
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Test
        run: cd build ; ctest -j$(nproc) --output-on-failure
