name: Valgrind

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang lld llvm cmake gtest valgrind

      - name: Configure
        run: cmake -S . -B build -DVALGRIND=ON
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config Release -j$(nproc)

      - name: Test
        run: cd build ; ctest -C Release -j$(nproc) --output-on-failure
