name: Valgrind

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt update
          sudo apt install gcc-10 g++-10 valgrind
          wget -q https://github.com/google/googletest/archive/release-1.10.0.zip
          unzip -q release-1.10.0.zip
          cd googletest-release-1.10.0
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_GMOCK=OFF \
          -DBUILD_SHARED_LIBS=ON -Dgtest_build_tests=OFF
          cmake --build build --config Release -j$(nproc)
          sudo cmake --build build --config Release --target install
          sudo ldconfig
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DKLIB_BUILD_TESTS=ON -DKLIB_VALGRIND=ON
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Build
        run: cmake --build build --config RelWithDebInfo -j$(nproc)

      - name: Test
        run: cd build ; ctest -C RelWithDebInfo -j$(nproc) --output-on-failure
